spring:
  application:
    name: asset-management-service
  datasource:
    url: jdbc:h2:mem:assetdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#  servlet:
#    multipart:
#      max-file-size: 100MB
#      max-request-size: 150MB
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  demo-data:
    enabled: true
    record-count: 25
    max-records:
      bank-accounts: 25
      bonds: 25
      invoices: 25
      stocks: 25
      real-estates: 25
      vehicles: 25
      trademarks: 25
      cash: 25
      inventories: 25
      machineries: 25
      brands: 25
      copyrights: 25
      patents: 25
      reputations: 25

